kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - name: traefik
        image: traefik:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: dashboard
          containerPort: 8080
          hostPort: 8080
        args:
        - --api.insecure
        - --accesslog
        - --entrypoints.http.Address=:80
        - --entrypoints.https.Address=:443
        - --providers.kubernetescrd=true
        - --api.dashboard=true
        - --log.level=INFO
        - --global.sendanonymoususage=false
        - --global.checknewversion=false
---
# A hello world Deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: hello-world:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
