# Connects Traefik with cloud provider's load balancer.
# All external traffic comes through here.
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
  selector:
    app: traefik
