# Connects Traefik with cloud provider's load balancer.
# All external traffic comes through here.
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8000
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
  - name: admin
    port: 80
    targetPort: 8080