kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
spec:
  basicAuth:
    users:
    # admin:password <do not use in production>
    # better way would be to use Secret
    - admin:$apr1$FGdrANYF$f0lAEDTXdWmxNfABopXX01
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-helloworld
  namespace: traefik
spec:
  entryPoints:
    - http
  routes:
  - match: Host(`carpenoctem.me`) && PathPrefix(`/hello`)
    kind: Rule
    services:
    - name: traefik-helloworld
      port: 80
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints: 
    - https
  tls:
    secretName: traefik-cert
  routes:
  - match: Host(`carpenoctem.com`) && PathPrefix(`/dashboard`)
    kind: Rule
    services:
    - name: traefik-dashboard
      port: 8080
      healthCheck:
        path: /dashboard/
        intervalSeconds: 3
        timeoutSeconds: 60
    middlewares:
    - name: traefik-dashboard-auth