apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`carpenoctem.me`) && PathPrefix(`/admin`)
    kind: Rule
    priority: 1
    services:
    - name: traefik-admin
      port: 8080
